name: Run tests

on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.lock
    - name: Pytest
      run: |
        pytest -v --cov=meteobeguda

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.lock
    - name: MyPy
      run: |
        mypy --ignore-missing-imports meteobeguda

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.lock
    - name: flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.lock
    - name: Bandit
      run: |
        bandit .

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.lock
    - name: Black
      run: |
        black --check .
