name: Run tests

on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: Pytest
      run: |
        uv run pytest -v --cov=src

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: MyPy
      run: |
        uv run mypy --ignore-missing-imports src

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: ruff
      run: |
        uv run ruff format --check .

  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: Bandit
      run: |
        uv run bandit .
