name: Take meteo snapshot

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Set up Python 3.12
      run: uv python install 3.12
    - name: Install dependencies
      run: |
        uv sync --all-extras
    - name: Fetch yesterday's data
      run: |
        uv run python etl.py
    - name: Commit new data & push
      run: |-
        git config user.name "Automated"
        git config user.name "actions@users.noreply.github.com"
        git add data/
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
