name: Take meteo snapshot

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: |
          requirements-dev.lock
          requirements.lock
    - name: Install dependencies
      run: |
        pip install -r requirements.lock
    - name: Fetch yesterday's data
      run: |
        python etl.py
    - name: Commit new data & push
      run: |-
        git config user.name "Automated"
        git config user.name "actions@users.noreply.github.com"
        git add data/
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
